---
title: dafzthomas.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
version: v3
name: Dafydd Thomas
email: dafz@thomasweb.co
description: Web developer.
avatar: https://avatars0.githubusercontent.com/u/7442896?v=3&s=240
url: https://old.dafzthomas.com
baseurl:
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
paginate: 5
paginate_path: "/blog/:num/"
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - sassc
  - octopress-autoprefixer
  - octopress-minify-html
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
